# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-04 19:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brevehome', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('desc', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('capacity', models.IntegerField()),
                ('public', models.BooleanField()),
                ('event_type', models.CharField(choices=[('B', 'Business'), ('C', 'Coding'), ('F', 'Fun'), ('E', 'Something Else')], default='C', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('desc', models.CharField(max_length=1023)),
                ('public', models.BooleanField()),
                ('profile_picture', models.BinaryField()),
                ('event_preference', models.CharField(choices=[('B', 'Business'), ('C', 'Coding'), ('F', 'Fun'), ('E', 'Something Else')], default='C', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('street1', models.CharField(max_length=255)),
                ('street2', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('zip_code', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='brevehome.Event')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=512)),
                ('birthday', models.DateTimeField()),
                ('desc', models.CharField(max_length=1023)),
                ('linkedin_url', models.CharField(max_length=255)),
                ('facebook_url', models.CharField(max_length=255)),
                ('instagram_url', models.CharField(max_length=255)),
                ('youtube_url', models.CharField(max_length=255)),
                ('twitter_url', models.CharField(max_length=255)),
                ('blog_url', models.CharField(max_length=255)),
                ('public', models.BooleanField()),
                ('profile_picture', models.BinaryField()),
                ('drink_preference', models.CharField(choices=[('C', 'Coffee'), ('T', 'Tea'), ('S', 'Soft Drink'), ('E', 'Something Else')], default='C', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('friends', models.ManyToManyField(related_name='_user_friends_+', to='brevehome.User')),
            ],
        ),
        migrations.RemoveField(
            model_name='admin',
            name='blogs',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='blog',
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.AddField(
            model_name='group',
            name='applicants',
            field=models.ManyToManyField(related_name='group_applications', to='brevehome.User'),
        ),
        migrations.AddField(
            model_name='group',
            name='invitees',
            field=models.ManyToManyField(related_name='group_invitations', to='brevehome.User'),
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(related_name='groups_joined', to='brevehome.User'),
        ),
        migrations.AddField(
            model_name='group',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups_owned', to='brevehome.User'),
        ),
        migrations.AddField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(related_name='events_attending', to='brevehome.User'),
        ),
        migrations.AddField(
            model_name='event',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events_owned', to='brevehome.User'),
        ),
        migrations.AddField(
            model_name='event',
            name='invitees',
            field=models.ManyToManyField(related_name='events_invited', to='brevehome.User'),
        ),
        migrations.AddField(
            model_name='event',
            name='possible_attendees',
            field=models.ManyToManyField(related_name='events_might_attend', to='brevehome.User'),
        ),
        migrations.AddField(
            model_name='comment',
            name='creator',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='brevehome.User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='message',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='brevehome.Event'),
            preserve_default=False,
        ),
    ]
